# Generated by Django 4.0.1 on 2022-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
