# Generated by Django 4.0.1 on 2022-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_refused',
            field=models.DateField(blank=True, null=True),
        ),
    ]
